<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ProductosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('productos')->insert([
            ['id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Intel Core i9-12900K', 'precio' => 393.99, 'imagenes' => '["intel_i9_12900k_1.webp", "intel_i9_12900k_2.webp"]', 'caracteristicas' => 'Procesador de 12 núcleos y 24 hilos, velocidad base de 3.2 GHz, tecnología Intel Turbo Boost, compatible con DDR5' ,'idAlmacen' => 1 ,'idCategoria' => 1],
            ['id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'AMD Ryzen 9 7900X', 'precio' => 382.99, 'imagenes' => '["amd_ryzen_9_7900x_1.webp", "amd_ryzen_9_7900x_2.webp"]', 'caracteristicas' => 'Procesador de 12 núcleos y 24 hilos, velocidad base de 3.8 GHz, tecnología AMD Precision Boost, compatible con PCIe 4.0' ,'idAlmacen' => 2 , 'idCategoria' => 1],
            ['id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Intel Core i7-12700K', 'precio' => 291.99, 'imagenes' => '["intel_i7_12700k_1.webp", "intel_i7_12700k_2.webp"]', 'caracteristicas' => 'Procesador de 8 núcleos y 16 hilos, velocidad base de 3.6 GHz, tecnología Intel Turbo Boost, compatible con DDR5' ,'idAlmacen' => 1 ,'idCategoria' => 1],
            ['id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'AMD Ryzen 7 7700', 'precio' => 329.99, 'imagenes' => '["amd_ryzen_7_7700_1.webp", "amd_ryzen_7_7700_2.webp"]', 'caracteristicas' => 'Procesador de 8 núcleos y 16 hilos, velocidad base de 3.6 GHz, tecnología AMD Precision Boost, compatible con PCIe 4.0' ,'idAlmacen' => 2 ,'idCategoria' => 1],
            ['id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'NVIDIA GeForce RTX 4080', 'precio' => 999.99, 'imagenes' => '["nvidia_rtx_4080_1.webp", "nvidia_rtx_4080_2.webp"]', 'caracteristicas' => 'Tarjeta gráfica con 16GB de memoria GDDR6X, soporte para Ray Tracing, NVIDIA DLSS 3.0, conectores HDMI y DisplayPort' ,'idAlmacen' => 1 ,'idCategoria' => 2],
            ['id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'AMD Radeon RX 7800 XT', 'precio' => 799.99, 'imagenes' => '["amd_rx_7800xt_1.jpg", "amd_rx_7800xt_2.jpg"]', 'caracteristicas' => 'Tarjeta gráfica con 12GB de memoria GDDR6, arquitectura RDNA 2, soporte para Ray Tracing, conectores HDMI y DisplayPort' ,'idAlmacen' => 2 ,'idCategoria' => 2],
            ['id' => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'NVIDIA GeForce RTX 4070 ti', 'precio' => 899.99, 'imagenes' => '["nvidia_rtx_4070_1.webp", "nvidia_rtx_4070_2.webp"]', 'caracteristicas' => 'Tarjeta gráfica con 12GB de memoria GDDR6X, soporte para Ray Tracing, NVIDIA DLSS 3.0, conectores HDMI y DisplayPort' ,'idAlmacen' => 1 ,'idCategoria' => 2],
            ['id' => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'AMD Radeon RX 7600 XT', 'precio' => 799.99, 'imagenes' => '["amd_rx_7600xt_1.jpg", "amd_rx_7600xt_2.jpg"]', 'caracteristicas' => 'Tarjeta gráfica con 8GB de memoria GDDR6, arquitectura RDNA 2, soporte para Ray Tracing, conectores HDMI y DisplayPort' ,'idAlmacen' => 2,'idCategoria' => 2],
            ['id' => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'ASUS ROG Strix Z590-E', 'precio' => 349.99, 'imagenes' => '["asus_rog_strix_z590e_1.webp", "asus_rog_strix_z590e_2.webp"]', 'caracteristicas' => 'Placa base ATX con chipset Z590, soporte para procesadores Intel de 10ª y 11ª generación, compatible con DDR4, conectores PCIe 4.0' ,'idAlmacen' => 2   ,'idCategoria' => 3],
            ['id' => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'MSI MPG B550 Gaming Edge', 'precio' => 179.99, 'imagenes' => '["msi_mpg_b550_1.webp", "msi_mpg_b550_2.webp"]', 'caracteristicas' => 'Placa base ATX con chipset B550, soporte para procesadores AMD Ryzen de 3ª generación, compatible con DDR4, conectores PCIe 4.0' ,'idAlmacen' => 3 ,'idCategoria' => 3],
            ['id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'ASUS TUF Gaming X570-Plus', 'precio' => 189.99, 'imagenes' => '["asus_tuf_x570_1.webp", "asus_tuf_x570_2.webp"]', 'caracteristicas' => 'Placa base ATX con chipset X570, soporte para procesadores AMD Ryzen de 3ª generación, compatible con DDR4, conectores PCIe 4.0' ,'idAlmacen' => 1 ,'idCategoria' => 3],
            ['id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'MSI MAG B460 TOMAHAWK', 'precio' => 129.99, 'imagenes' => '["msi_mag_b460_1.webp", "msi_mag_b460_2.webp"]', 'caracteristicas' => 'Placa base ATX con chipset B460, soporte para procesadores Intel de 10ª generación, compatible con DDR4, conectores PCIe 3.0' ,'idAlmacen' => 4 ,'idCategoria' => 3],
            ['id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'G.Skill Trident Z RGB 32GB', 'precio' => 199.99, 'imagenes' => '["gskill_trident_z_32gb_1.webp", "gskill_trident_z_32gb_2.webp"]', 'caracteristicas' => 'Kit de memoria RAM DDR4 3200MHz, iluminación RGB, latencia CL16, disipador de calor' ,'idAlmacen' => 2 ,'idCategoria' => 4],
            ['id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Corsair Vengeance LPX 16GB', 'precio' => 89.99, 'imagenes' => '["corsair_vengeance_lpx_16gb_1.webp", "corsair_vengeance_lpx_2.webp"]', 'caracteristicas' => 'Kit de memoria RAM DDR4 3000MHz, latencia CL16, disipador de calor de perfil bajo' ,'idAlmacen' => 4 ,'idCategoria' => 4],
            ['id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'G.Skill Ripjaws V 16GB', 'precio' => 79.99, 'imagenes' => '["gskill_ripjaws_v_16gb_1.webp", "gskill_ripjaws_v_2.webp"]', 'caracteristicas' => 'Kit de memoria RAM DDR4 3200MHz, latencia CL16, diseño de disipador agresivo' ,'idAlmacen' => 1 ,'idCategoria' => 4],
            ['id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Corsair Dominator Platinum 32GB', 'precio' => 249.99, 'imagenes' => '["corsair_dominator_32gb_1.webp", "corsair_dominator_32gb_2.webp"]', 'caracteristicas' => 'Kit de memoria RAM DDR4 3200MHz, iluminación RGB, latencia CL14, disipador de aluminio' ,'idAlmacen' => 3 ,'idCategoria' => 4],
            ['id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Seagate BarraCuda 2TB', 'precio' => 59.99, 'imagenes' => '["seagate_barracuda_2tb_1.webp", "seagate_barracuda_2tb_2.webp"]', 'caracteristicas' => 'Disco duro HDD de 2TB, 7200 RPM, caché de 256MB, interfaz SATA 6Gb/s' ,'idAlmacen' => 2 ,'idCategoria' => 5],
            ['id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Western Digital Blue 1TB', 'precio' => 49.99, 'imagenes' => '["wd_blue_1tb_1.webp", "wd_blue_1tb_2.webp"]', 'caracteristicas' => 'Disco duro HDD de 1TB, 7200 RPM, caché de 64MB, interfaz SATA 6Gb/s' ,'idAlmacen' => 1 ,'idCategoria' => 5],
            ['id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Seagate FireCuda 520 1TB', 'precio' => 149.99, 'imagenes' => '["seagate_firecuda_1tb_1.webp", "seagate_firecuda_1tb_2.webp"]', 'caracteristicas' => 'Disco SSD NVMe de 1TB, velocidad de lectura hasta 5000 MB/s, interfaz PCIe Gen4 x4' ,'idAlmacen' => 4 ,'idCategoria' => 5],
            ['id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Western Digital Black 2TB', 'precio' => 129.99, 'imagenes' => '["wd_black_2tb_1.webp", "wd_black_2tb_2.webp"]' , 'caracteristicas' => 'Disco duro HDD de 2TB, 7200 RPM, caché de 256MB, interfaz SATA 6Gb/s' ,'idAlmacen' => 2 ,'idCategoria' => 5],
            ['id' => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'iPhone 15 Pro Max', 'precio' => 1299.99, 'imagenes' => '["iphone_15_promax_1.webp", "iphone_15_promax_2.webp"]', 'caracteristicas' => 'Smartphone con pantalla de 6.7 pulgadas, almacenamiento de 256GB, cámara triple de 12MP, Face ID' ,'idAlmacen' => 3 ,'idCategoria' => 20],
            ['id' => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Samsung Galaxy S24 Ultra', 'precio' => 1199.99, 'imagenes' => '["samsung_galaxy_s24ultra_1.webp", "samsung_galaxy_s24ultra_2.webp"]', 'caracteristicas' => 'Smartphone con pantalla de 6.8 pulgadas, almacenamiento de 256GB, cámara cuádruple de 108MP, reconocimiento de huella digital' ,'idAlmacen' => 1 ,'idCategoria' => 20],
            ['id' => 23, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Google Pixel 8 Pro', 'precio' => 999.99, 'imagenes' => '["google_pixel_8pro_1.webp", "google_pixel_8pro_2.webp"]', 'caracteristicas' => 'Smartphone con pantalla de 6.7 pulgadas, almacenamiento de 128GB, cámara dual de 50MP, Android 14' ,'idAlmacen' => 3 ,'idCategoria' => 20],
            ['id' => 24, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Xiaomi Mi 14', 'precio' => 899.99, 'imagenes' => '["xiaomi_mi_14_1.webp", "xiaomi_mi_14_2.webp"]', 'caracteristicas' => 'Smartphone con pantalla de 6.6 pulgadas, almacenamiento de 128GB, cámara triple de 108MP, MIUI 15' ,'idAlmacen' => 3 ,'idCategoria' => 20],
            ['id' => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Sony Xperia 3', 'precio' => 799.99, 'imagenes' => '["sony_xperia_3_1.webp", "sony_xperia_3_2.webp"]', 'caracteristicas' => 'Smartphone con pantalla de 6.5 pulgadas, almacenamiento de 128GB, cámara triple de 12MP, sonido Hi-Res Audio' ,'idAlmacen' => 4 ,'idCategoria' => 20],
            ['id' => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'nombre' => 'Intel Core i9-13900K', 'precio' => 799.99, 'imagenes' => '["intel_i9_13900k_1.webp", "intel_i9_13900k_2.webp"]', 'caracteristicas' => 'Procesador de 24 núcleos y 32 hilos, velocidad base de 3.0 GHz, tecnología Intel Turbo Boost Max, compatible con DDR5' ,'idAlmacen' => 2 ,'idCategoria' => 1]
        ]);
    }
}
